# Part 1: ACME Relational Database Design with PostgreSQL

## Data Exploration to Determine Schema Design

In [2]:
import pandas as pd
import os

# Resolve data/ whether the kernel cwd is the repo root or notebooks/
_repo_candidates = [
    os.path.join(os.getcwd(), "data"),
    os.path.join(os.getcwd(), "..", "data"),
]
csv_path = next((p for p in _repo_candidates if os.path.isdir(p)), os.path.join("..", "data"))
csv_path = os.path.abspath(csv_path)
print(f"Loading CSVs from: {csv_path}")

customers_df = pd.read_csv(os.path.join(csv_path, 'customers.csv'))
phones_df = pd.read_csv(os.path.join(csv_path, 'customer_phones.csv'))
emails_df = pd.read_csv(os.path.join(csv_path, 'customer_emails.csv'))
addresses_df = pd.read_csv(os.path.join(csv_path, 'customer_addresses.csv'))
products_df = pd.read_csv(os.path.join(csv_path, 'products.csv'))
purchases_df = pd.read_csv(os.path.join(csv_path, 'purchases.csv'))
ratings_df = pd.read_csv(os.path.join(csv_path, 'user_ratings.csv'))

In [3]:
# TODO: explore datasets to identify schema needs (create more cells as needed)

dataframes = {
    'customers' : customers_df,
    'phones' : phones_df,
    'emails' : emails_df,
    'addresses': addresses_df,
    'products' : products_df,
    'purchases':purchases_df,
    'ratings' : ratings_df
}

for name, df in dataframes.items():
    print(f"==== {name} Table ====")
    print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
    print("Columns & inferred types:")
    print(df.dtypes)
    print("\nSample Data:")
    display(df.head())
    print('-' * 50)

==== customers Table ====
Rows: 15, Columns: 4
Columns & inferred types:
customer_id     int64
first_name     object
last_name      object
created_at     object
dtype: object

Sample Data:

   customer_id first_name   last_name           created_at
0            1      Alice  Wonderland  2024-01-15 10:30:00
1            2        Bob    Martinez  2024-01-16 11:45:00
2            3    Charlie   Chocolate  2024-01-17 09:20:00
3            4    Dorothy        Gale  2024-01-18 14:15:00
4            6      Frodo     Baggins  2024-01-20 08:45:00

--------------------------------------------------
==== phones Table ====
Rows: 19, Columns: 4
Columns & inferred types:
phone_id        int64
customer_id     int64
phone          object
created_at     object
dtype: object

Sample Data:

   phone_id  customer_id     phone           created_at
0         1            1  555-0101  2024-01-15 10:30:00
1         2            1  555-0102  2024-01-15 10:31:00
2         3            2  555-0103  2024-01-16 11:45:00
3         4            3  555-0104  2024-01-17 09:20:00
4         5            3  555-0105  2024-01-17 09:21:00

--------------------------------------------------
==== emails Table ====
Rows: 16, Columns: 4
Columns & inferred types:
email_id        int64
customer_id     int64
email          object
created_at     object
dtype: object

Sample Data:

   email_id  customer_id                           email           created_at
0         1            1           alice@wonderland.fake  2024-01-15 10:30:00
1         2            1      alice.curious@example.test  2024-01-15 10:31:00
2         3            2               bob@martinez.fake  2024-01-16 11:45:00
3         4            3  charlie@chocolate-factory.test  2024-01-17 09:20:00
4         5            4            dorothy@oz-land.fake  2024-01-18 14:15:00

--------------------------------------------------
==== addresses Table ====
Rows: 32, Columns: 4
Columns & inferred types:
address_id      int64
customer_id     int64
address        object
created_at     object
dtype: object

Sample Data:

   address_id  customer_id                    address           created_at
0           1            1         1 Rabbit Hole Lane  2024-01-15 10:30:00
1           2            1        42 Tea Party Circle  2024-01-15 10:31:00
2           3            2  123 Construction Site Ave  2024-01-16 11:45:00
3          21            2          456 Toolbox Drive  2024-01-16 11:46:00
4           4            3     456 Candy Factory Road  2024-01-17 09:20:00

--------------------------------------------------
==== products Table ====
Rows: 2, Columns: 7
Columns & inferred types:
product_id          int64
product_name       object
product_type       object
description        object
price             float64
stock_quantity      int64
created_at         object
dtype: object

Sample Data:

,product_id,product_name,product_type,description,price,stock_quantity,created_at
0,1,Industrial Large Gear,large_gear,Heavy-duty large gear for industrial applications,450.0,50,2024-01-01 08:00:00
1,2,Precision Small Gear,small_gear,Precision small gear for detailed work,75.0,200,2024-01-01 08:00:00

--------------------------------------------------
==== purchases Table ====
Rows: 21, Columns: 9
Columns & inferred types:
purchase_id                int64
customer_id                int64
large_gear_quantity        int64
small_gear_quantity        int64
large_gear_unit_price    float64
small_gear_unit_price    float64
total_price              float64
purchase_date             object
status                    object
dtype: object

Sample Data:

,purchase_id,customer_id,large_gear_quantity,small_gear_quantity,large_gear_unit_price,small_gear_unit_price,total_price,purchase_date,status
0,1,1,2,10,450.0,75.0,1650.0,2024-02-01 10:30:00,completed
1,2,2,0,5,0.0,75.0,375.0,2024-02-01 11:15:00,completed
2,3,3,1,8,450.0,75.0,1050.0,2024-02-01 14:20:00,completed
3,4,4,3,0,450.0,0.0,1350.0,2024-02-02 09:45:00,completed
4,6,6,0,12,0.0,75.0,900.0,2024-02-02 15:10:00,completed

--------------------------------------------------
==== ratings Table ====
Rows: 15, Columns: 6
Columns & inferred types:
rating_id       int64
customer_id     int64
product_id      int64
rating          int64
review_text    object
rating_date    object
dtype: object

Sample Data:

,rating_id,customer_id,product_id,rating,review_text,rating_date
0,1,1,1,5,Excellent quality large gear. Very durable.,2024-02-05 10:30:00
1,2,1,2,4,Good small gear for the price.,2024-02-05 10:35:00
2,3,2,2,5,Perfect for high-speed operations!,2024-02-06 11:15:00
3,4,3,1,4,Solid performance on large gear.,2024-02-06 14:20:00
4,5,3,2,3,Decent small gear but could be better.,2024-02-06 14:25:00

--------------------------------------------------

### Rigorous Key and Constraint Validations

In [4]:
# =========================================================================
#  Primary Key Constraint Validation
# =========================================================================

print("=" * 60)
print("LAYER 1: PHYSICAL PRIMARY KEY UNIQUENESS CHECKS")
print("=" * 60)

pk_checks = [
    ("Customers", customers_df, "customer_id"),
    ("Products", products_df, "product_id"),
    ("Purchases", purchases_df, "purchase_id"),
    ("Phones", phones_df, "phone_id"),
    ("Emails", emails_df, "email_id"),
    ("Addresses", addresses_df, "address_id"),
    ("Ratings", ratings_df, "rating_id")
]

for name, df, pk in pk_checks:
    is_unique = df[pk].is_unique
    null_count = df[pk].isnull().sum()
    print(f"[{name}] Column '{pk}': Unique? {is_unique} | Null values? {null_count}")

============================================================
LAYER 1: PHYSICAL PRIMARY KEY UNIQUENESS CHECKS
============================================================
[Customers] Column 'customer_id': Unique? True | Null values? 0
[Products] Column 'product_id': Unique? True | Null values? 0
[Purchases] Column 'purchase_id': Unique? True | Null values? 0
[Phones] Column 'phone_id': Unique? True | Null values? 0
[Emails] Column 'email_id': Unique? True | Null values? 0
[Addresses] Column 'address_id': Unique? True | Null values? 0
[Ratings] Column 'rating_id': Unique? True | Null values? 0

### Duplication Checks

In [5]:
print("\n" + "=" * 60)
print("LAYER 2: LOGICAL BUSINESS RULE & DUPLICATION CHECKS")
print("=" * 60)

# Check 1: Do we have duplicate phone numbers for the same customer?
dup_phones = phones_df.duplicated(subset=['customer_id', 'phone']).sum()
print(f"Duplicate (customer_id, phone) pairs in Phones: {dup_phones}")

# Check 2: Do we have duplicate emails for the same customer?
dup_emails = emails_df.duplicated(subset=['customer_id', 'email']).sum()
print(f"Duplicate (customer_id, email) pairs in Emails: {dup_emails}")

# Check 3: Do we have duplicate addresses for the same customer?
dup_addresses = addresses_df.duplicated(subset=['customer_id', 'address']).sum()
print(f"Duplicate (customer_id, address) pairs in Addresses: {dup_addresses}")

# Check 4: Has any customer rated the same product more than once?
dup_ratings = ratings_df.duplicated(subset=['customer_id', 'product_id']).sum()
print(f"Duplicate (customer_id, product_id) rating attempts in Ratings: {dup_ratings}")

============================================================
LAYER 2: LOGICAL BUSINESS RULE & DUPLICATION CHECKS
============================================================
Duplicate (customer_id, phone) pairs in Phones: 0
Duplicate (customer_id, email) pairs in Emails: 0
Duplicate (customer_id, address) pairs in Addresses: 0
Duplicate (customer_id, product_id) rating attempts in Ratings: 0

### Referential Checks

In [6]:
print("\n" + "=" * 60)
print("LAYER 3: REFERENTIAL INTEGRITY (ORPHAN ROW DETECTIVE)")
print("=" * 60)

parent_customers = set(customers_df['customer_id'])
parent_products = set(products_df['product_id'])

# Check if any child tables reference a customer_id that doesn't exist in Customers
child_customer_tables = {
    "Phones": phones_df,
    "Emails": emails_df,
    "Addresses": addresses_df,
    "Purchases": purchases_df,
    "Ratings": ratings_df
}

for name, df in child_customer_tables.items():
    orphans = df[~df['customer_id'].isin(parent_customers)]
    print(f"[{name}] Rows referencing non-existent customer_id: {len(orphans)}")

# Check if child tables reference a product_id that doesn't exist in Products
child_product_tables = {
    "Ratings": ratings_df
}

for name, df in child_product_tables.items():
    orphans = df[~df['product_id'].isin(parent_products)]
    print(f"[{name}] Rows referencing non-existent product_id: {len(orphans)}")

============================================================
LAYER 3: REFERENTIAL INTEGRITY (ORPHAN ROW DETECTIVE)
============================================================
[Phones] Rows referencing non-existent customer_id: 0
[Emails] Rows referencing non-existent customer_id: 0
[Addresses] Rows referencing non-existent customer_id: 0
[Purchases] Rows referencing non-existent customer_id: 0
[Ratings] Rows referencing non-existent customer_id: 0
[Ratings] Rows referencing non-existent product_id: 0

## Relational Schema DDL

In [7]:
%load_ext sql
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

print("Connected to PostgreSQL")

Connecting to 'postgresql://postgres:***@127.0.0.1:5432/postgres'

Connected to PostgreSQL

In [11]:
%%sql
-- Drop existing tables to start fresh
DROP TABLE IF EXISTS user_ratings CASCADE;
DROP TABLE IF EXISTS purchases CASCADE;
DROP TABLE IF EXISTS customer_addresses CASCADE;
DROP TABLE IF EXISTS customer_emails CASCADE;
DROP TABLE IF EXISTS customer_phones CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- TODO: write your queries here
-- Core Customer table
CREATE TABLE Customers(
  customer_id INT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

-- Core Products table
CREATE TABLE Products(

    product_id INT PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    product_type VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL CHECK(price >= 0.00),
    stock_quantity INT NOT NULL CHECK(stock_quantity >= 0),
    created_at TIMESTAMP NOT NULL
);

-- Customer Contact Channels (one - many relationships)
CREATE TABLE Customer_Phones(
    
    phone_id INT PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES Customers(customer_id) on DELETE CASCADE,
    phone VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_phone UNIQUE (customer_id , phone)

);

CREATE TABLE Customer_Emails(
    
    email_id INT PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES Customers(customer_id) on DELETE CASCADE,
    email VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_email UNIQUE (customer_id , email)

);

CREATE TABLE Customer_Addresses (
    
    address_id INT PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES Customers(customer_id) ON DELETE CASCADE,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_address UNIQUE (customer_id, address)
);

-- 4. REFACTORED: Purchases Table (3NF-compliant Transaction Ledger)
-- Replaces rigid 'gear' columns with a direct Product Foreign Key reference.
-- The total_price column is intentionally stored as an immutable transaction audit 
-- snapshot. While it equals quantity * unit_price at execution time, storing it explicitly
-- preserves point-in-time financial records against future catalog price adjustments or 
-- historical overrides.
CREATE TABLE Purchases(
    purchase_id INT,
    customer_id INT NOT NULL REFERENCES Customers(customer_id) ON DELETE RESTRICT,
    product_id INT NOT NULL REFERENCES Products(product_id) ON DELETE RESTRICT,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(10, 2) NOT NULL CHECK (unit_price >= 0.00),
    total_price DECIMAL(10, 2) NOT NULL CHECK (total_price >= 0.00),
    purchase_date TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (purchase_id, product_id) -- 3NF Composite Line-Item Key
);

-- Ratings table (many - many feedback junction)

CREATE TABLE User_Ratings (
    
    rating_id INT PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES Customers(customer_id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES Products(product_id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    rating_date TIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_product_rating UNIQUE (customer_id, product_id)
);

Empty DataFrame
Columns: []
Index: []

## Loading Test Data

In [12]:
from sqlalchemy import create_engine, inspect as sa_inspect, text

engine = create_engine('postgresql://postgres:postgres@127.0.0.1:5432/postgres')

# Comment out any tables you haven't created yet to build up your schema gradually
tables = [
    "customers",
    "customer_phones",
    "customer_emails",
    "customer_addresses",
    "products",
    "purchases",
    "user_ratings",
]

# Verify all tables in the list exist before attempting to load
existing = sa_inspect(engine).get_table_names()
missing = [t for t in tables if t not in existing]
if missing:
    raise RuntimeError(f"Tables not found: {missing} — run your CREATE TABLE DDL first.")

# Print column types and primary/foreign keys for each table
print("Schema overview:")
with engine.connect() as conn:
    for table in tables:
        print(f"\n  {table}")
        cols = conn.execute(text(
            "SELECT column_name, data_type FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = :t ORDER BY ordinal_position"
        ), {"t": table})
        for col in cols:
            print(f"    {col.column_name}: {col.data_type}")
        keys = conn.execute(text(
            "SELECT tc.constraint_type, kcu.column_name "
            "FROM information_schema.table_constraints tc "
            "JOIN information_schema.key_column_usage kcu "
            "  ON tc.constraint_name = kcu.constraint_name "
            "  AND tc.table_schema = kcu.table_schema "
            "WHERE tc.table_schema = 'public' AND tc.table_name = :t "
            "AND tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY') "
            "ORDER BY tc.constraint_type, kcu.column_name"
        ), {"t": table})
        for key in keys:
            print(f"    [{key.constraint_type}] {key.column_name}")

# Load data with 3NF Transformations
print("\nLoading data...")
for table in tables:
    csv_file_path = os.path.join(csv_path, f'{table}.csv')
    
    # -------------------------------------------------------------------------
    # Scenario A: Standard Tables (Direct Load)
    # -------------------------------------------------------------------------
    if table not in ["products", "purchases"]:
        df = pd.read_csv(csv_file_path)
        df.to_sql(table, engine, if_exists='append', index=False)
        print(f"  {table}.csv → {table} table (Directly loaded)")
        
    # -------------------------------------------------------------------------
    # Scenario B: Products Ingestion (Ensuring 3NF Catalog Items exist)
    # -------------------------------------------------------------------------
    elif table == "products":
        # Ensure our gear definitions are explicitly present in the catalog
        # to satisfy foreign key checks in the purchases ledger
        gear_products = pd.DataFrame([
            {
                "product_id": 104,
                "product_name": "Large Gear",
                "product_type": "Industrial Component",
                "description": "Heavy-duty 3D printed mechanical gear",
                "price": 50.00,
                "stock_quantity": 100,
                "created_at": pd.Timestamp.now()
            },
            {
                "product_id": 105,
                "product_name": "Small Gear",
                "product_type": "Precision Component",
                "description": "High-precision 3D printed micro gear",
                "price": 25.00,
                "stock_quantity": 250,
                "created_at": pd.Timestamp.now()
            }
        ])
        
        # Load custom products if they exist in a CSV, otherwise load gears
        if os.path.exists(csv_file_path):
            df = pd.read_csv(csv_file_path)
            # Combine the CSV catalog with the gear definition dataframe, removing duplicates
            df = pd.concat([df, gear_products]).drop_duplicates(subset=['product_id'])
        else:
            df = gear_products
            
        df.to_sql("products", engine, if_exists='append', index=False)
        print("  Gears & Catalog Products → products table (3NF catalog established)")
        
         # -------------------------------------------------------------------------
    # Scenario C: Purchases Transformation (Unpivoting Flat Gears to Line Items)
    # -------------------------------------------------------------------------
    elif table == "purchases":
        df_flat = pd.read_csv(csv_file_path)
        normalized_records = []
        
        # Unpivot each flat row into individual line items
        for _, row in df_flat.iterrows():
            # Check for Large Gear purchase
            if row.get("large_gear_quantity", 0) > 0:
                qty = int(row["large_gear_quantity"])
                unit_price = float(row.get("large_gear_unit_price", 50.00))
                normalized_records.append({
                    "purchase_id": row["purchase_id"],
                    "customer_id": row["customer_id"],
                    "product_id": 104,  # Large Gear ID
                    "quantity": qty,
                    "unit_price": unit_price,
                    "total_price": qty * unit_price,
                    "purchase_date": row["purchase_date"],
                    "status": row["status"]
                })
                
            # Check for Small Gear purchase
            if row.get("small_gear_quantity", 0) > 0:
                qty = int(row["small_gear_quantity"])
                unit_price = float(row.get("small_gear_unit_price", 25.00))
                normalized_records.append({
                    "purchase_id": row["purchase_id"],
                    "customer_id": row["customer_id"],
                    "product_id": 105,  # Small Gear ID
                    "quantity": qty,
                    "unit_price": unit_price,
                    "total_price": qty * unit_price,
                    "purchase_date": row["purchase_date"],
                    "status": row["status"]
                })
        
        df_normalized = pd.DataFrame(normalized_records)
        df_normalized.to_sql("purchases", engine, if_exists='append', index=False)
        print(f"  {table}.csv → transformed into {len(df_normalized)} 3NF line items → purchases table")

print("\n" + "="*50)
print("DATABASE INITIALIZATION & 3NF DATA LOAD: SUCCESSFUL")
print("="*50)

Schema overview:

  customers
    customer_id: integer
    first_name: character varying
    last_name: character varying
    created_at: timestamp without time zone
    [PRIMARY KEY] customer_id

  customer_phones
    phone_id: integer
    customer_id: integer
    phone: character varying
    created_at: timestamp without time zone
    [FOREIGN KEY] customer_id
    [PRIMARY KEY] phone_id

  customer_emails
    email_id: integer
    customer_id: integer
    email: character varying
    created_at: timestamp without time zone
    [FOREIGN KEY] customer_id
    [PRIMARY KEY] email_id

  customer_addresses
    address_id: integer
    customer_id: integer
    address: character varying
    created_at: timestamp without time zone
    [FOREIGN KEY] customer_id
    [PRIMARY KEY] address_id

  products
    product_id: integer
    product_name: character varying
    product_type: character varying
    description: text
    price: numeric
    stock_quantity: integer
    created_at: timestamp without time zone
    [PRIMARY KEY] product_id

  purchases
    purchase_id: integer
    customer_id: integer
    product_id: integer
    quantity: integer
    unit_price: numeric
    total_price: numeric
    purchase_date: timestamp without time zone
    status: character varying
    [FOREIGN KEY] customer_id
    [FOREIGN KEY] product_id
    [PRIMARY KEY] product_id
    [PRIMARY KEY] purchase_id

  user_ratings
    rating_id: integer
    customer_id: integer
    product_id: integer
    rating: integer
    review_text: text
    rating_date: timestamp without time zone
    [FOREIGN KEY] customer_id
    [FOREIGN KEY] product_id
    [PRIMARY KEY] rating_id

Loading data...
  customers.csv → customers table (Directly loaded)
  customer_phones.csv → customer_phones table (Directly loaded)
  customer_emails.csv → customer_emails table (Directly loaded)
  customer_addresses.csv → customer_addresses table (Directly loaded)
  Gears & Catalog Products → products table (3NF catalog established)
  purchases.csv → transformed into 31 3NF line items → purchases table
  user_ratings.csv → user_ratings table (Directly loaded)

==================================================
DATABASE INITIALIZATION & 3NF DATA LOAD: SUCCESSFUL
==================================================

## Querying Test Data in Database

In [13]:
counts = {}
with engine.connect() as conn:
    for table in tables:
        result = conn.execute(text(f"SELECT COUNT(*) FROM {table}"))
        counts[table] = result.scalar()

print("Row counts:")
for table in tables:
    print(f"  {counts[table]:>4}  {table}")

Row counts:
    15  customers
    19  customer_phones
    16  customer_emails
    32  customer_addresses
     4  products
    31  purchases
    15  user_ratings

---

# Part 2: ACME 3D Printing NoSQL Database Design with MongoDB

In [10]:
from pymongo import MongoClient
from datetime import datetime
import json

def get_mongo_connection():
    """Create a MongoDB connection"""
    try:
        client = MongoClient('mongodb://root:root@127.0.0.1:27017/?authSource=admin')  # Update with your connection string
        db = client['acme_3d_printing']
        print("Connected to MongoDB")
        return db
    except Exception as e:
        print(f"Error connecting to MongoDB: {e}")
        return None
    
# Drop MongoDB collections if they exist (to start fresh)
db = get_mongo_connection()
if db is not None:
    db.customers.drop()
    db.products.drop()
    db.purchases.drop()
    print("Dropped existing MongoDB collections")

Connected to MongoDB
Dropped existing MongoDB collections

## Customer Collection

In [11]:
# TODO: create one or more customer documents (Python dictionaries) that represent
# your customer schema design
# 1. Customer Document A: Alice Wonderland (Aerospace Industry)
customer_alice = {
    "customer_id": 1,
    "first_name": "Alice",
    "last_name": "Wonderland",
    "email": "alice@aerospace-wholesalers.test",
    "phone": "555-0101",
    "address": "1 Rabbit Hole Lane",
    "customer_industry": "Aerospace",
    
    # "In Your Industry" Page Pre-computation Pattern
    # Embedded product structures specifically matching her "Aerospace" industry
    "industry_recommendations": [
        {
            "product_id": 101,
            "product_name": "Titanium Aerospace Bracket",
            "material": "Titanium Ti-6Al-4V",
            "tensile_strength_mpa": 950
        },
        {
            "product_id": 103,
            "product_name": "Carbon Fiber Drone Joint",
            "material": "Carbon-Reinforced Nylon",
            "infill_density": "80%"
        }
    ],
    
    # Orders Page: Subset Pattern (Max 10 latest purchases)
    "latest_purchases": [
        {
            "purchase_id": 901,
            "product_id": 101,
            "product_name": "Titanium Aerospace Bracket",
            "quantity": 2,
            "unit_price": 1200.00,
            "purchase_date": datetime(2026, 8, 10, 14, 0, 0)
        },
        {
            "purchase_id": 902,
            "product_id": 103,
            "product_name": "Carbon Fiber Drone Joint",
            "quantity": 5,
            "unit_price": 150.00,
            "purchase_date": datetime(2026, 8, 11, 9, 30, 0)
        }
    ],
    "created_at": datetime.now()
}

# 2. Customer Document B: Bob Martinez (Medical Industry)
customer_bob = {
    "customer_id": 2,
    "first_name": "Bob",
    "last_name": "Martinez",
    "email": "bob@medical-3dprinting-specialists.test",
    "phone": "555-0103",
    "address": "123 Construction Site Ave",
    "customer_industry": "Medical",
    
    # "In Your Industry" Page Pre-computation Pattern
    # Embedded product structures specifically matching his "Medical" industry
    "industry_recommendations": [
        {
            "product_id": 102,
            "product_name": "Biocompatible Surgical Guide",
            "material": "Dental SG Resin",
            "sterilizable": True
        }
    ],
    
    # Orders Page: Subset Pattern (Max 10 latest purchases)
    "latest_purchases": [
        {
            "purchase_id": 903,
            "product_id": 102,
            "product_name": "Biocompatible Surgical Guide",
            "quantity": 1,
            "unit_price": 850.00,
            "purchase_date": datetime(2026, 8, 12, 10, 15, 0)
        }
    ],
    "created_at": datetime.now()
}

# Wrap both documents in a list for clean batch ingestion
customers_data = [customer_alice, customer_bob]

## Product Collection

In [12]:
# TODO: create at least two product documents (Python dictionaries) that represent
# the different types of products that your product schema supports

# Product 1: High-performance Aerospace bracket (Metal DMLS Printing)
product_aerospace_bracket = {
    "product_id" : 101,
    "product_name" : "Titanium Aerospace Bracket",
    "product_intended_industry": "Aerospace",
    "attributes": {
        "material": "Titanium Ti-6Al-4v",
        "tensile_strength_mpa": 950,
        "weight_grams": 340,
        "dimensions_mm":{"x":120, "y":80,"z":45}
    },
    "created_at":datetime.now()
}

# Product 2: Biocompatible Medical guide (SLA Resin Printing)
product_medical_guide = {
    "product_id": 102,
    "product_name": "Biocompatible Surgical Guide",
    "product_intended_industry": "Medical",
    "attributes": {
        "material": "Dental SG Resin",
        "sterilizable": True,
        "color": "Translucent Amber",
        "layer_height_microns": 50
    },
    "created_at": datetime.now()
}

# Product 3: Carbon-reinforced aerospace drone joint (FDM Composite Printing)
product_drone_joint = {
    "product_id": 103,
    "product_name": "Carbon Fiber Drone Joint",
    "product_intended_industry": "Aerospace",
    "attributes": {
        "material": "Carbon-Reinforced Nylon",
        "infill_density": "80%",
        "flexural_modulus_gpa": 8.5
    },
    "created_at": datetime.now()
}

# Wrap these diverse catalog documents in a list for database ingestion
products_data = [product_aerospace_bracket, product_medical_guide, product_drone_joint]

## Purchases Collection

In [13]:
# TODO: create one or more purchase documents (Python dictionaries) that represent
# your purchase schema design

# Purchase 1: Historical bulk transaction for Alice (customer_id: 1)
# referencing the Titanium Aerospace Bracket (product_id: 101)
purchase_historical_alice = {
    "purchase_id": 401,                   # Surrogate Primary Key
    "customer_id": 1,                     # Reference Link to db.customers
    "product_id": 101,                    # Reference Link to db.products
    "purchase_date": datetime(2025, 6, 15, 10, 0, 0),
    "quantity": 12,                       # Bulk corporate order
    "unit_price": 1200.00,
    "total_price": 14400.00,
    "status": "completed",
    
    # Demonstration of NoSQL schema flexibility in transaction logs
    "custom_specifications": {             
        "tolerance_required": "+/- 0.05mm",
        "finishing_process": "Bead Blasting"
    },
    "created_at": datetime.now()
}

# Purchase 2: Historical transaction for Bob (customer_id: 2)
# referencing the Biocompatible Surgical Guide (product_id: 102)
purchase_historical_bob = {
    "purchase_id": 402,                   # Surrogate Primary Key
    "customer_id": 2,                     # Reference Link to db.customers
    "product_id": 102,                    # Reference Link to db.products
    "purchase_date": datetime(2025, 12, 20, 11, 30, 0),
    "quantity": 3,
    "unit_price": 850.00,
    "total_price": 2550.00,
    "status": "completed",
    
    # Dynamic attributes specific to surgical fabrication tracking
    "custom_specifications": {
        "autoclave_safe": True,
        "sterilization_batch_id": "ST-99201"
    },
    "created_at": datetime.now()
}

# Wrap both historical documents in a list for clean batch ingestion
purchases_data = [purchase_historical_alice, purchase_historical_bob]

## Loading Collections into MongoDB

In [14]:
# TODO: use insert_one or insert_many to load your collections into MongoDB

if db is not None:
    print("MongoDb connection is active. Commencing data load...\n")
    
    # 1. Load customers data
    customers_result = db.customers.insert_many(customers_data)
    print(f"Successfully loaded {len(customers_result.inserted_ids)} customer records into 'db.customers'.")
    print(f"  Inserted IDs: {customers_result.inserted_ids}\n")
    
    # 2. Load Products data
    products_result = db.products.insert_many(products_data)
    print(f"Successfully loaded {len(products_result.inserted_ids)} product records into 'db.products'.")
    print(f"  Inserted IDs: {products_result.inserted_ids}\n")
    
    # 3. Load Purchases data
    purchases_result = db.purchases.insert_many(purchases_data)
    print(f"Successfully loaded {len(purchases_result.inserted_ids)} historical purchase logs into 'db.purchases'.")
    print(f"  Inserted IDs: {purchases_result.inserted_ids}\n")
    
    print("=" * 60)
    print("DATABASE INGESTION STATUS: SUCCESS")
    print("=" * 60)
else:
    print("Error: Active MongoDB database connection ('db') not found. Please run your connection cell first.")

MongoDb connection is active. Commencing data load...

Successfully loaded 2 customer records into 'db.customers'.
  Inserted IDs: [ObjectId('6a7e20f76e70240f96e5d1d5'), ObjectId('6a7e20f76e70240f96e5d1d6')]

Successfully loaded 3 product records into 'db.products'.
  Inserted IDs: [ObjectId('6a7e20f76e70240f96e5d1d7'), ObjectId('6a7e20f76e70240f96e5d1d8'), ObjectId('6a7e20f76e70240f96e5d1d9')]

Successfully loaded 2 historical purchase logs into 'db.purchases'.
  Inserted IDs: [ObjectId('6a7e20f76e70240f96e5d1da'), ObjectId('6a7e20f76e70240f96e5d1db')]

============================================================
DATABASE INGESTION STATUS: SUCCESS
============================================================

## NoSQL Modeling Design Decisions

1. **Why are recent purchases and industry products embedded in the customer document?**

Recent purchases and industry recommendations are embedded directly into the customer document to optimize for read heavy query patterns on key user facing pages (such as the account dashboard, order history preview).

2. **What are the trade-offs of embedding vs. referencing?**

Embedding (Denormalization):

Pros: Optimized read performance (single lookup returns all required data), eliminates complex $lookup aggregation joins, and aligns well with document-oriented data locality.

Cons: Potential data duplication, risk of data staleness (e.g., if a product name or price changes, embedded copies must be updated), and document size growth (subject to MongoDB's 16MB document size limit).

Referencing (Normalization):

Pros: Eliminates data redundancy, guarantees strong data consistency (updates happen in one central document), and prevents document size bloat for unbounded relationships (like unlimited historical purchases).

Cons: Requires multiple network round-trips or $lookup pipeline stages to assemble full objects, resulting in higher query latency for UI rendering.

3. **How does this schema handle products with different attributes?**

This schema leverages MongoDB's polymorphic sub-document pattern through the flexible attributes object.

Because NoSQL databases are schema-agnostic, products across distinct industries do not need to share a rigid set of columns:

An Aerospace product can store structural parameters like tensile_strength_mpa, weight_grams, and 3D dimensions (x, y, z).

A Medical product can dynamically store domain-specific flags such as sterilizable: true, layer_height_microns, or color.

This flexibility allows ACME to introduce entirely new product types with unique manufacturing specs into the products collection without requiring schema migrations, ALTER TABLE statements, or sparse NULL columns.

## MongoDB Demonstration Queries

In [15]:
# TODO: write 2 or more queries that demonstrate how your collections
# can be used by application code

if db is not None:
    
    # Query 1: "In your Industry Page"
    print("="*70)
    print("Query 1: 'In Your Industry' Page Landing")
    print("=" * 70)
    
    # Filter for customer Alice
    customer_filter = {"customer_id":1}
    
    # Projection to specify which attributes to include
    customer_projection = {
        "_id": 0,
        "first_name": 1,
        "last_name": 1,
        "customer_industry": 1,
        "industry_recommendations": 1
    }
    
    aerospace_customer = db.customers.find_one(customer_filter, customer_projection)
    print("Returned pre-computed industry payload:")
    print(json.dumps(aerospace_customer, indent=2, default=str))
    print("\n" + "-" * 70 + "\n")
    
    
    # Query 2 : Catalog Page
    print("=" * 70)
    print("Query 2: 'Catalog Page' Search")
    print("=" * 70)
    
    # Filter using dot notation to drill inton flexible attributes section
    product_filter = {"attributes.sterilizable": True}
    product_projection = {
        "_id": 0,
        "product_id": 1,
        "product_name": 1,
        "attributes.material": 1,
        "attributes.sterilizable": 1
    }
    
    # Using find to return a cursor and iterate 
    medical_products_cursor = db.products.find(product_filter, product_projection)
    print("Matching biocompatible catalog results:")
    for prod in medical_products_cursor:
        print(json.dumps(prod, indent=2, default=str))
    print("\n" + "-" * 70 + "\n")
    
    
    # Quey 3: Bulk historical Transaction Audit
    print("=" * 70)
    print("QUERY 3: BULK HISTORICAL TRANSACTIONS")
    print("=" * 70)


    # Filter for orders where quantity is strictly greeater than 10
    bulk_filter = {"quantity": {"$gt": 10}}
    
     # Project key fields that exist natively on the purchase record (hiding internal MongoDB IDs)
    bulk_projection = {
        "_id": 0,
        "purchase_id": 1,
        "customer_id": 1,
        "product_id": 1,
        "quantity": 1,
        "total_price": 1,
        "status": 1
      }
    
    bulk_cursor = db.purchases.find(bulk_filter, bulk_projection)
    print("Found raw historical bulk transactions (referencing raw customer/product IDs):")
    for record in bulk_cursor:
        print(f"  Purchase ID: {record['purchase_id']} | Customer ID Ref: {record['customer_id']} | Product ID Ref: {record['product_id']} | Qty: {record['quantity']} | Total: ${record['total_price']:.2f}")
    

    # Query 4: Referencing Resolution of customer and Product information
    print("\n" + "=" * 70)
    print("QUERY 4: BULK HISTORICAL TRANSACTIONS (Dereferenced via $lookup Join)")
    print("=" * 70)
    
    pipeline = [
        # Stage 1: Match bulk transactions first to leverage indexing on the quantity field
        {
            "$match" : {"quantity" : {"$gt": 10}}
        },
        
        # Stage 2: Left-Outer Join with 'customers' to resolve 'customer_id' [8, 92]
        {
            "$lookup" :{
                "from" : "customers",   
                "localField" : "customer_id",
                "foreignField": "customer_id",
                "as" : "customer_info"
            }
        },
        
        # Stage 3: Left-Outer Join with 'products' to resolve 'product_id' [8, 92]
        {
            "$lookup": {
               "from": "products",            
               "localField": "product_id",    
               "foreignField": "product_id",  
               "as": "product_info"           
            }
        },
        
        # Stage 4: Unwind (flatten) the lookup arrays since joins return list values [8, 92]
        {"$unwind": "$customer_info"},
        {"$unwind": "$product_info"},
        
        # Stage 5: Project a clean invoice dataset for application consumption [8, 92]
        {
            "$project": {
                "_id": 0,
                "purchase_id": 1,
                "quantity": 1,
                "total_price": 1,
                "purchase_date": 1,
                 # Synthesise buyer's full name from the joined customer profile
                "customer_name": {"$concat": ["$customer_info.first_name", " ", "$customer_info.last_name"]},
                 # Pull product name from the joined polymorphic product catalog
                "product_name": "$product_info.product_name"
             }
         }

    ]
    
    # Run the aggregation pipleine against the purchases collection
    joined_results = list(db.purchases.aggregate(pipeline))
    
    print("Fully dereferenced bulk invoice records:")
    for invoice in joined_results:
        print(f"  Invoice #{invoice['purchase_id']} | Date: {invoice['purchase_date'].strftime('%Y-%m-%d')} | Buyer: {invoice['customer_name']} | Product: {invoice['product_name']} | Qty: {invoice['quantity']} | Total: ${invoice['total_price']:.2f}")

======================================================================
Query 1: 'In Your Industry' Page Landing
======================================================================
Returned pre-computed industry payload:
{
  "first_name": "Alice",
  "last_name": "Wonderland",
  "customer_industry": "Aerospace",
  "industry_recommendations": [
    {
      "product_id": 101,
      "product_name": "Titanium Aerospace Bracket",
      "material": "Titanium Ti-6Al-4V",
      "tensile_strength_mpa": 950
    },
    {
      "product_id": 103,
      "product_name": "Carbon Fiber Drone Joint",
      "material": "Carbon-Reinforced Nylon",
      "infill_density": "80%"
    }
  ]
}

----------------------------------------------------------------------

======================================================================
Query 2: 'Catalog Page' Search
======================================================================
Matching biocompatible catalog results:
{
  "product_id": 102,
  "product_name": "Biocompatible Surgical Guide",
  "attributes": {
    "material": "Dental SG Resin",
    "sterilizable": true
  }
}

----------------------------------------------------------------------

======================================================================
QUERY 3: BULK HISTORICAL TRANSACTIONS
======================================================================
Found raw historical bulk transactions (referencing raw customer/product IDs):
  Purchase ID: 401 | Customer ID Ref: 1 | Product ID Ref: 101 | Qty: 12 | Total: $14400.00

======================================================================
QUERY 4: BULK HISTORICAL TRANSACTIONS (Dereferenced via $lookup Join)
======================================================================
Fully dereferenced bulk invoice records:
  Invoice #401 | Date: 2025-06-15 | Buyer: Alice Wonderland | Product: Titanium Aerospace Bracket | Qty: 12 | Total: $14400.00

---

# Part 3: Graph Database Design with Neo4j

In [16]:
# Setup: Import Neo4j libraries and establish connection.
# Hint: This code is provided for you in the reference guide, but feel free to modify it if needed.
from neo4j import GraphDatabase

class Neo4jConnection:
    def __init__(self):
        self.driver = GraphDatabase.driver("bolt://127.0.0.1:7687", auth=("neo4j", "neo4jpass"))

    def close(self):
        self.driver.close()

    def execute_query(self, query, parameters=None):
        with self.driver.session() as session:
            result = session.run(query, parameters)
            return [record for record in result]

# Connect to Neo4j
neo4j_conn = Neo4jConnection()

# Drop all Neo4j nodes and relationships (to start fresh)
try:
    neo4j_conn.execute_query("MATCH (n) DETACH DELETE n")
    print("Deleted all existing Neo4j nodes and relationships")
except Exception as e:
    print(f"Note: {e}")

Deleted all existing Neo4j nodes and relationships

## Node Types

In [17]:
# TODO: write Cypher CREATE statements for your nodes (create more cells as needed)

# Defining Node Types (Customers, Products, Industries)

create_nodes_query = """
// 1. Create Industry nodes
MERGE (aero:Industry {name:"Aerospace"})
MERGE (med:Industry {name:"Medical"})

// 2. Create Customer nodes
MERGE (alice:Customer { customer_id: 1, first_name: "Alice", last_name: "Wonderland", email: "alice@aerospace-wholesalers.test", phone: "555-0101" })
MERGE (bob:Customer { customer_id: 2, first_name: "Bob", last_name: "Martinez", email: "bob@medical-3dprinting-specialists.test", phone: "555-0103" })

// 3. Create Product nodes (with base_price and description)
MERGE (p101:Product { 
  product_id: 101, 
  product_name: "Titanium Aerospace Bracket", 
  material: "Titanium Ti-6Al-4V", 
  tensile_strength_mpa: 950,
  base_price: 1200.00,
  description: "High-strength titanium bracket engineered for aerospace load-bearing applications."
})

MERGE (p102:Product { 
  product_id: 102, 
  product_name: "Biocompatible Surgical Guide", 
  material: "Dental SG Resin", 
  sterilizable: true,
  base_price: 850.00,
  description: "Autoclavable resin guide designed for precision medical and surgical positioning."
})

MERGE (p103:Product { 
  product_id: 103, 
  product_name: "Carbon Fiber Drone Joint", 
  material: "Carbon-Reinforced Nylon", 
  infill_density: "80%",
  base_price: 150.00,
  description: "Lightweight carbon-reinforced composite joint for drone structural assembly."
})

MERGE (p104:Product { 
  product_id: 104, 
  product_name: "Titanium Dental Implant", 
  material: "Medical Titanium", 
  sterilizable: true,
  base_price: 650.00,
  description: "Biocompatible titanium dental implant designed for medical applications."
})
"""

try:
    neo4j_conn.execute_query(create_nodes_query)
    print("Customer, Product, Industry nodes merged successfully")
except Exception as e:
    print(f"Error creating node : {e}")

Customer, Product, Industry nodes merged successfully

## Relationships

In [18]:
# TODO: write Cypher CREATE statements for your relationships (create more cells as needed)

create_relationships_query = """
// 1. MATCH all required nodes first
MATCH (alice:Customer {customer_id: 1})
MATCH (bob:Customer {customer_id: 2})
MATCH (aero:Industry {name: "Aerospace"})
MATCH (med:Industry {name: "Medical"})
MATCH (p101:Product {product_id: 101})
MATCH (p102:Product {product_id: 102})
MATCH (p103:Product {product_id: 103})
MATCH (p104:Product {product_id: 104})

// 2. Map relationships between Customers and Industries
MERGE (alice)-[:WORKS_IN]->(aero)
MERGE (bob)-[:WORKS_IN]->(med)

// 3. Map Products to Industries they serve
MERGE (p101)-[:SERVES]->(aero)
MERGE (p102)-[:SERVES]->(med)
MERGE (p103)-[:SERVES]->(aero)
MERGE (p104)-[:SERVES]->(med)

// 4. Create PURCHASED relationships with transaction properties
MERGE (alice)-[:PURCHASED { purchase_id: 901, date: "2026-08-10", quantity: 2, unit_price: 1200.00, total_price: 2400.00, status: "completed" }]->(p101)
MERGE (alice)-[:PURCHASED { purchase_id: 902, date: "2026-08-11", quantity: 5, unit_price: 150.00, total_price: 750.00, status: "completed" }]->(p103)
MERGE (alice)-[:PURCHASED { purchase_id: 401, date: "2025-06-15", quantity: 12, unit_price: 1200.00, total_price: 14400.00, status: "archived" }]->(p101)
MERGE (alice)-[:PURCHASED { purchase_id: 904, date: "2026-08-13", quantity: 1, unit_price: 850.00, total_price: 850.00, status: "completed" }]->(p102)
MERGE (bob)-[:PURCHASED { purchase_id: 903, date: "2026-08-12", quantity: 1, unit_price: 850.00, total_price: 850.00, status: "completed" }]->(p102)

// 5. Create bidirectional ALSO_BOUGHT relationships between products
MERGE (p101)-[:ALSO_BOUGHT {confidence: 0.85, support_count: 142}]->(p103)
MERGE (p103)-[:ALSO_BOUGHT {confidence: 0.85, support_count: 142}]->(p101)
MERGE (p102)-[:ALSO_BOUGHT {confidence: 0.78, support_count: 95}]->(p101)
MERGE (p102)-[:ALSO_BOUGHT {confidence: 0.65, support_count: 40}]->(p103)
"""

try:
    neo4j_conn.execute_query(create_relationships_query)
    print("Node relationships and transaction properties merged successfully")
except Exception as e:
    print(f"Error creating relationship : {e}")

Node relationships and transaction properties merged successfully

## Recommendation Queries

### Customers who bought X also bought Y (Required)

In [19]:
# TODO: write your "people also purchased" recommendation query (create more cells as needed)
# =========================================================================
# Method 1: COLLABORATIVE FILTERING VIA ALSO_BOUGHT EDGES
# =========================================================================


also_bought_query = """
MATCH (c:Customer {customer_id: $customer_id}) - [:PURCHASED] -> (p1:Product) - [r:ALSO_BOUGHT] -> (rec:Product)
WHERE NOT (c) - [:PURCHASED] -> (rec)
RETURN p1.product_name AS BecauseYouBought,
       rec.product_name AS RecommendedProduct,
       r.confidence AS ConfidenceScore,
       r.support_count AS SupportCount
ORDER BY ConfidenceScore DESC
"""

try:
    print("=" *80)
    print("METHOD 1:Collaborative filtering via precomputed ALSO_BOUGHT edges")
    print("=" * 80)
    results = neo4j_conn.execute_query(also_bought_query, {"customer_id": 2})
    
    for r in results:
        print(f"  Since you bought '{r['BecauseYouBought']}':")
        print(f"    ↳ We recommend '{r['RecommendedProduct']}'")
        print(f"      [Confidence: {r['ConfidenceScore']:.0%}, Co-purchased {r['SupportCount']} times]\n")
except Exception as e:
    print(f"Error executing Method 1: {e}")
    
    
# =========================================================================
# METHOD 2 (OPTIMISED): DYNAMIC COLLABORATIVE FILTERING
# =========================================================================

dynamic_collab_query = """
// Step 1: Single-path traversal tracing: My Purchases ➔ Shared Buyers ➔ Their Purchases
MATCH (c1:Customer {customer_id: $customer_id})-[:PURCHASED]->(p1:Product)<-[:PURCHASED]-(c2:Customer)-[:PURCHASED]->(p2:Product)

// Step 2: Ensure we exclude Alice herself, self-matching items, and items she already bought
WHERE c1 <> c2 
  AND p1 <> p2 
  AND NOT (c1)-[:PURCHASED]->(p2)

// Step 3: Aggregate the overlapping customer count and sort by recommendation strength
RETURN p1.product_name AS BecauseYouBought,
       p2.product_name AS RecommendedProduct,
       count(DISTINCT c2) AS SharedBuyersCount
ORDER BY SharedBuyersCount DESC
"""

try:
    print("=" * 80)
    print("METHOD 2 (OPTIMISED): DYNAMIC CO-PURCHASE TRAVERSAL")
    print("=" * 80)
    results = neo4j_conn.execute_query(dynamic_collab_query, {"customer_id": 2})
    
    if results:
        for r in results:
            print(f"  Since you bought '{r['BecauseYouBought']}':")
            print(f"    ↳ We recommend '{r['RecommendedProduct']}'")
            print(f"      [Recommended by {r['SharedBuyersCount']} other customer(s) who bought both]\n")
    else:
        print("  No dynamic co-purchases found (requires overlapping customer transactions).")
    print("=" * 80)
except Exception as e:
    print(f"Error executing Method 2: {e}")

================================================================================
METHOD 1:Collaborative filtering via precomputed ALSO_BOUGHT edges
================================================================================
  Since you bought 'Biocompatible Surgical Guide':
    ↳ We recommend 'Titanium Aerospace Bracket'
      [Confidence: 78%, Co-purchased 95 times]

  Since you bought 'Biocompatible Surgical Guide':
    ↳ We recommend 'Carbon Fiber Drone Joint'
      [Confidence: 65%, Co-purchased 40 times]

================================================================================
METHOD 2 (OPTIMISED): DYNAMIC CO-PURCHASE TRAVERSAL
================================================================================
  Since you bought 'Biocompatible Surgical Guide':
    ↳ We recommend 'Titanium Aerospace Bracket'
      [Recommended by 1 other customer(s) who bought both]

  Since you bought 'Biocompatible Surgical Guide':
    ↳ We recommend 'Carbon Fiber Drone Joint'
      [Recommended by 1 other customer(s) who bought both]

================================================================================

### Popular products in your industry (Optional Standout)

In [20]:
# TODO (Optional Standout): write your industry recommendation query (create more cells as needed)
# =========================================================================
# STANDOUT QUERY: POPULAR PRODUCTS IN YOUR INDUSTRY SECTOR
# =========================================================================

industry_popularity_query = """
// Step 1: Traverse from the customer to their industry, and find products serving that industry
MATCH (c:Customer {customer_id: $customer_id})-[:WORKS_IN]->(i:Industry)<-[:SERVES]-(recProduct:Product)

// Step 2: Dynamically filter out any products the starting customer has already purchased
WHERE NOT (c)-[:PURCHASED]->(recProduct)

// Step 3: Optionally match other customers' purchases of these candidate products to calculate popularity
OPTIONAL MATCH (:Customer)-[pur:PURCHASED]->(recProduct)

// Step 4: Group, aggregate total units sold, and return the ranked recommendation list
RETURN recProduct.product_name AS RecommendedProduct,
       recProduct.material AS Material,
       i.name AS Sector,
       sum(coalesce(pur.quantity, 0)) AS TotalUnitsSold
ORDER BY TotalUnitsSold DESC
"""

try:
    print("=" * 80)
    print("EXECUTING INDUSTRY-ALIGNMENT POPULARITY ENGINE")
    print("=" * 80)
    
    # Let's test this for Customer ID: 2 (Bob Martinez - Medical Sector)
    # Since Bob has bought the Surgical Guide (ID 102), this should return zero 
    # recommendations unless there is another medical product he hasn't bought.
    # Let's test it for Customer ID: 1 (Alice - Aerospace Sector) to see her suggestions:
    target_customer_id = 2
    results = neo4j_conn.execute_query(industry_popularity_query, {"customer_id": target_customer_id})
    
    print(f"Popular Industry Recommendations for Customer #{target_customer_id}:")
    if results:
        for r in results:
            print(f"  ↳ Product: {r['RecommendedProduct']}")
            print(f"    Sector: {r['Sector']} | Material: {r['Material']}")
            print(f"    Total Volume Sold to Others: {r['TotalUnitsSold']} unit(s)\n")
    else:
        print("  No new unpurchased products found serving this customer's industry sector.\n")
    print("=" * 80)
except Exception as e:
    print(f"Error executing industry popularity query: {e}")

================================================================================
EXECUTING INDUSTRY-ALIGNMENT POPULARITY ENGINE
================================================================================
Popular Industry Recommendations for Customer #2:
  ↳ Product: Titanium Dental Implant
    Sector: Medical | Material: Medical Titanium
    Total Volume Sold to Others: 0 unit(s)

================================================================================

### Products similar to X (Optional Standout)

In [21]:
# TODO (Optional Standout): write your product similarity query (create more cells as needed)

# =========================================================================
# STANDOUT QUERY: PRODUCT SIMILARITY ENGINE (CONTENT & BEHAVIORAL MIX)
# =========================================================================

similarity_query = """
// Step 1: Find the target product and traverse to find peer products serving the same industry
MATCH (target:Product {product_id: $product_id})-[:SERVES]->(i:Industry)<-[:SERVES]-(similar:Product)

// Step 2: Ensure we don't match the target product with itself
WHERE target <> similar

// Step 3: Check if there is also an ALSO_BOUGHT co-purchase relationship between them (behavioral overlay)
OPTIONAL MATCH (target)-[r:ALSO_BOUGHT]->(similar)

// Step 4: Return similarity metrics, projecting shared metadata and co-purchase scores
RETURN target.product_name AS TargetProduct,
       similar.product_name AS SimilarProduct,
       i.name AS SharedSector,
       similar.material AS SimilarMaterial,
       coalesce(r.confidence, 0.0) AS CoPurchaseConfidence
ORDER BY CoPurchaseConfidence DESC
"""

try:
    print("=" * 80)
    print("EXECUTING MULTI-DIMENSIONAL PRODUCT SIMILARITY ENGINE")
    print("=" * 80)
    
    # Let's find products similar to our "Titanium Aerospace Bracket" (ID: 101)
    target_product_id = 101
    results = neo4j_conn.execute_query(similarity_query, {"product_id": target_product_id})
    
    if results:
        print(f"Products similar to '{results[0]['TargetProduct']}':\n")
        for r in results:
            print(f"  ↳ Similar Item: {r['SimilarProduct']}")
            print(f"    Reason: Both serve the '{r['SharedSector']}' sector")
            print(f"    Material: {r['SimilarMaterial']}")
            if r['CoPurchaseConfidence'] > 0:
                print(f"    Behavioral Match: Frequently bought together! (Confidence: {r['CoPurchaseConfidence']:.0%})\n")
            else:
                print(f"    Behavioral Match: None (Great candidate to bundle together!)\n")
    else:
        print("  No similar products found.")
    print("=" * 80)
except Exception as e:
    print(f"Error executing product similarity query: {e}")

================================================================================
EXECUTING MULTI-DIMENSIONAL PRODUCT SIMILARITY ENGINE
================================================================================
Products similar to 'Titanium Aerospace Bracket':

  ↳ Similar Item: Carbon Fiber Drone Joint
    Reason: Both serve the 'Aerospace' sector
    Material: Carbon-Reinforced Nylon
    Behavioral Match: Frequently bought together! (Confidence: 85%)

================================================================================

## Graph Design Decisions

1. **What nodes and relationships did you create and why?**

Node Types:

Customer: Represents buyers in the system (properties: customer_id, first_name, last_name, email, phone).

Product: Represents the 3D-printed catalog items (properties: product_id, product_name, material, tensile_strength_mpa, sterilizable, infill_density).

Industry: Represents industry sectors served by ACME (properties: name, e.g., Aerospace, Medical)

Relationship Types:

(:Customer)-[:WORKS_IN]->(:Industry): Connects customers to their professional industry domain for domain-targeted filtering and recommendations.

(:Product)-[:SERVES]->(:Industry): Categorizes products by the specific industry application they are engineered for.

(:Customer)-[:PURCHASED]->(:Product): Tracks transactional history between customers and products, capturing point-in-time purchase metadata.

(:Product)-[:ALSO_BOUGHT]->(:Product): Direct product-to-product edge used for collaborative filtering recommendations.

Why: Graph databases excel at traversing relationships. Separating entities into discrete node labels connected by semantic relationships allows us to perform real-time recommendation traversals without heavy relational JOIN operations.

2. **How does your graph structure enable the "people also purchased" recommendation?**

Our graph structure enables collaborative filtering through two distinct patterns:Pre-computed Edges (ALSO_BOUGHT):Traverses directly from a product the customer bought to candidate items via precomputed co-purchase links:$$\text{(Customer)} \xrightarrow{\text{:PURCHASED}} \text{(Product A)} \xrightarrow{\text{:ALSO\_BOUGHT}} \text{(Product B)}$$This approach provides ultra-low latency reads ($O(1)$ lookup per item) for real-time recommendation engines.Dynamic Path Traversal:Traverses through shared buyer history in real time:$$\text{(Customer 1)} \xrightarrow{\text{:PURCHASED}} \text{(Product A)} \xleftarrow{\text{:PURCHASED}} \text{(Customer 2)} \xrightarrow{\text{:PURCHASED}} \text{(Product B)}$$By finding overlapping buyers ($\text{Customer 2}$) who bought the same initial product ($\text{Product A}$), the graph dynamically identifies and ranks unpurchased peer items ($\text{Product B}$)

3. **What properties did you add to relationships and why?**

PURCHASED Relationship Properties:

purchase_id, date, quantity, unit_price, total_price, status.

Why: In graph modeling, edge-level attributes capture the context of an interaction. Storing transaction details directly on the PURCHASED edge avoids creating separate, heavy transaction nodes for simpler models while allowing temporal filtering (e.g., filtering purchases within a specific date range).

ALSO_BOUGHT Relationship Properties:

confidence (float, e.g., 0.85), support_count (integer, e.g., 142).

Why: Storing statistical weights directly on the relationship allows the Cypher engine to ORDER BY ConfidenceScore DESC and restrict recommendations to high-confidence co-purchases without re-calculating statistics on every query.

4. **How would you handle graph growth as more customers and products are added?**

Indexing & Constraints:

Create uniqueness constraints and B-tree indexes on primary identifiers (Customer.customer_id, Product.product_id, Industry.name) to guarantee fast MATCH lookups as node counts scale into millions.

Relationship Pruning & Thresholding:

Filter out low-confidence ALSO_BOUGHT edges (e.g., only retain edges where confidence >= 0.5 or support_count >= 10) during offline batch ETL runs to prevent excessive graph dense-node degradation (supernodes).

Graph Partitioning & Read Replicas:

Deploy a Neo4j Causal Clustering topology with dedicated Read Replicas to scale read-heavy recommendation traffic horizontally across servers.

## Optional Standout: GraphRAG with Neo4j + Vector Search

This section uses `utils/graphrag_chatbot.py` (included in this repo) plus a Vocareum-routed OpenAI key.

**Setup**

1. Copy `.env.example` → `.env` and set `VOCAREUM_API_KEY` (never commit `.env`).
2. Ensure Docker Neo4j is running and Parts 1–3 graph data are loaded.
3. Run from `notebooks/` or the repo root; the import path resolves either way.

Requires packages: `neo4j`, `openai` (see `requirements.txt`).

In [ ]:
# Import GraphRAG chatbot (repo helper under utils/)
import sys
import os

# Make repo root importable whether cwd is notebooks/ or project root
_candidates = [
    os.path.abspath(os.getcwd()),
    os.path.abspath(os.path.join(os.getcwd(), "..")),
]
for _root in _candidates:
    if os.path.isdir(os.path.join(_root, "utils")) and _root not in sys.path:
        sys.path.insert(0, _root)
        break

from utils.graphrag_chatbot import Neo4jGraphRAG

print("Neo4j GraphRAG with vector search ready")

In [ ]:
# Optional: load .env from repo root if python-dotenv is installed
try:
    from dotenv import load_dotenv
    for _env in [
        os.path.join(os.getcwd(), ".env"),
        os.path.join(os.getcwd(), "..", ".env"),
    ]:
        if os.path.isfile(_env):
            load_dotenv(_env)
            break
except ImportError:
    pass

# Requires VOCAREUM_API_KEY in the environment (or .env). Never hardcode keys.
# Vocareum routes OpenAI-compatible API requests.

if "VOCAREUM_API_KEY" not in os.environ:
    print("VOCAREUM_API_KEY is not set. Export it or add it to a local .env file.")
    print("GraphRAG cells will be skipped.")
    chatbot = None
else:
    try:
        chatbot = Neo4jGraphRAG(
            neo4j_uri="bolt://127.0.0.1:7687",
            neo4j_user="neo4j",
            neo4j_password="neo4jpass",
            api_key=os.environ["VOCAREUM_API_KEY"],
            base_url="https://openai.vocareum.com/v1",
        )
        print("GraphRAG initialized with vector search")
        print(f"Model: {chatbot.model}")

        print("\n Creating product embeddings...")
        chatbot.embed_products()

    except Exception as e:
        print(f"\n Error: {e}")
        chatbot = None

In [ ]:
if chatbot:
    customer_id = 1  # Update to match a customer_id in your graph
    # Example questions to try:
    #   "What products are available?"
    #   "What products are popular in my industry?"
    #   "What are the best products for aerospace companies?"
    print("Chat with your graph database. Type 'q' to quit.\n")
    while True:
        question = input("You: ").strip()
        if question.lower() == "q":
            break
        if question:
            response = chatbot.chat(question, customer_id=customer_id)
            print(f"Assistant: {response}\n")
else:
    print("Chatbot not initialized — set VOCAREUM_API_KEY and re-run the GraphRAG setup cells.")

In [ ]:
# Clean up: Close GraphRAG / Neo4j drivers when present
if "chatbot" in dir() and chatbot:
    chatbot.close()
    print("GraphRAG Neo4j connection closed")

if "neo4j_conn" in dir() and neo4j_conn:
    neo4j_conn.close()
    print("Neo4j connection closed")